<?php

use Illuminate\Database\Seeder;
use App\Shoe;
use App\ShoeBrand;

class ShoeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {   
        $shoes = [
            ['Agus', '1027'],
            ['Agus', '2004'],
            ['Agus', '241'],
            ['Agus', '408'],
            ['Agus', '432'],
            ['Agus', '765'],
            ['Agus', '814'],
            ['Agus', '818'],
            ['Ale', '07'],
            ['Beira rio', '4194.702'],
            ['Beira rio', '8290.608'],
            ['Beira rio', '8381.106'],
            ['Carpincho', 'Canastita'],
            ['Chiczone', 'Querike'],
            ['Citadina', 'Betina'],
            ['Citadina', 'Vella'],
            ['Citadina', 'Vissia'],
            ['Comoditas', '366'],
            ['Crislor', '110'],
            ['Crislor', '120'],
            ['Crislor', '4005'],
            ['Crislor', '401'],
            ['Crislor', 'F100'],
            ['Crislor', 'F40'],
            ['Crislor', 'Heroes20'],
            ['Crislor', 'Ice'],
            ['Diana', '2006'],
            ['Diana', '2019'],
            ['Diana', '2019c'],
            ['Diana', '2020'],
            ['Diana', '2020c'],
            ['Flywing', '5177'],
            ['Footy', 'Fx291'],
            ['Footy', 'Fx308'],
            ['Footy', 'Fx309'],
            ['Footy', 'Fx311'],
            ['Footy', 'Fx313'],
            ['Goosy', '1617'],
            ['Goosy', '52220'],
            ['Gowell', '2018'],
            ['Gowell', '2027'],
            ['Havaiana', 'Brasil'],
            ['Havaiana', 'Slim organic'],
            ['Havaiana', 'Slim thematic'],
            ['Hey day', '000'],
            ['Hey day', '002'],
            ['Hey day', '071'],
            ['Hey day', '088'],
            ['Hey day', '097'],
            ['Hey day', '100'],
            ['Hey day', '108'],
            ['Hey day', '118'],
            ['Hey day', '119'],
            ['Hey day', '124'],
            ['Hey day', '130'],
            ['Hey day', '131'],
            ['Hey day', '138'],
            ['Hey day', '141'],
            ['Hey day', '143'],
            ['Hey day', '144'],
            ['Hey day', '145'],
            ['Ipanema', '06466'],
            ['Ipanema', '25971'],
            ['Ipanema', '26026'],
            ['Jaguar', '128'],
            ['Jaguar', '148'],
            ['Jaguar', '201'],
            ['Jaguar', '205'],
            ['Jaguar', '507'],
            ['Jaguar', '530'],
            ['Jaguar', '9018'],
            ['Jaguar', '9025'],
            ['Jaguar', '9026'],
            ['Jaguar', '905'],
            ['Jaguar', '906'],
            ['Jaguar', '907'],
            ['Jaguar', '910'],
            ['Jaguar', '928'],
            ['Jaguar', '960'],
            ['Jamaiquinas', 'Sapito'],
            ['Junior', '107'],
            ['Junior', '111'],
            ['Junior', '550araña'],
            ['Junior', '65'],
            ['Keek', '900'],
            ['Korek', '317'],
            ['Kyrios', '410'],
            ['Kyrios', '540'],
            ['Lady stork', 'Barbara'],
            ['Lady stork', 'Pura'],
            ['Le utopik', 'Sidney'],
            ['Le utopik', 'Sidneyup'],
            ['Le utopik', 'Stylo'],
            ['Lualma', '1210'],
            ['Lualma', '301'],
            ['Lualma', '324'],
            ['Lualma', 'Air'],
            ['Lualmi', 'Airniño'],
            ['Mistral', '6152'],
            ['Modare', '7113.100'],
            ['Modare', '7123.107'],
            ['Molekinha', '2118.119'],
            ['Molekinha', '2128.309'],
            ['Molekinha', '2524.306'],
            ['Molekinho', '2141.102'],
            ['Movida kids', '07'],
            ['Movida kids', '67'],
            ['Namoro', '1619'],
            ['Native', '715'],
            ['Neo', 'L1'],
            ['Neo', 'L3'],
            ['New tilers', '702.2'],
            ['None', 'None'],
            ['Piavitelli', 'Aruba'],
            ['Piavitelli', 'Pira'],
            ['Rave', '026'],
            ['Rave', '027'],
            ['Rave', '043'],
            ['Rave', '045'],
            ['Rave', '073'],
            ['Rave', '10'],
            ['Rave', '1000'],
            ['Rave', '1018'],
            ['Rave', '1019'],
            ['Rave', '1020'],
            ['Rave', '1024'],
            ['Rave', '2000'],
            ['Rave', '2001'],
            ['Rave', '2002'],
            ['Rave', '201'],
            ['Rave', '202'],
            ['Rave', '534'],
            ['Rave', '543'],
            ['Rave', '552'],
            ['Rave', '553'],
            ['Rave', '561'],
            ['Rave', '571'],
            ['Rave', '61'],
            ['Rave', '610'],
            ['Rave', '75'],
            ['Rave', '76'],
            ['Rave', '80'],
            ['Rave', '800'],
            ['Rave', '801'],
            ['Rave', '802'],
            ['Rave', '803'],
            ['Rave', '82'],
            ['Rave', '83'],
            ['Rave', '84'],
            ['Rave', '980'],
            ['Rave', '990'],
            ['Rave', '992'],
            ['Rave', '993'],
            ['Rave', '998'],
            ['Rave', '999'],
            ['Rinar', '200'],
            ['Rinar', '250'],
            ['Rinar', '350'],
            ['Savage', 'Kata301'],
            ['Sea walk', '100'],
            ['Sea walk', '260'],
            ['Sea walk', 'Cross b'],
            ['Shadow', '4000'],
            ['Soft', '05'],
            ['Soft', '06'],
            ['Soft', '110'],
            ['Soft', '3400'],
            ['Soft', '3450'],
            ['Soft', '3600'],
            ['Soft', '3900'],
            ['Soft', '3920'],
            ['Soft', '3950'],
            ['Soft', '4000'],
            ['Soft', '5000'],
            ['Soft', '5050'],
            ['Soft', '5100'],
            ['Soft', '5200'],
            ['Soft', '5300'],
            ['Soft', '5400'],
            ['Soft', '5500'],
            ['Vaner', '3510'],
            ['Vaner', 'C590'],
            ['Vaner', 'Zb300'],
            ['Vaner', 'Zc592'],
            ['Vaner', 'Zis630'],
            ['Vaner', 'Zs246'],
            ['Vaner', 'Zs730'],
            ['Viamarte', '11201'],
            ['Viamarte', '11751'],
            ['Viamarte', '19701'],
            ['Viamarte', '21571'],
            ['Viamarte', '6301'],
            ['Vizzano', '1298.100'],
            ['Winpie', '122'],
            ['Winpie', '193'],
            ['Winpie', '195'],
            ['Winpie', '20'],
            ['Winpie', '235'],
            ['Winpie', '322'],
            ['Winpie', '420'],
            ['Winpie', '620'],
            ['Winpie', '680'],
        ];

        $brands = ShoeBrand::select('name', 'id')->get();

        foreach($shoes as $shoe) {
            $i = 0;
            while($i < count($brands) && $shoe[0] != $brands[$i]->name) {
                $i++;
            }
            $new = new Shoe();
            $new->id_brand = $brands[$i]->id;
            $new->code = $shoe[1];
            $new->save();
        }
    }
}
