<?php

use Illuminate\Database\Seeder;
use App\ShoeColor;
class ShoeColorTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {   
        $colors = [
            "Aero",
            "Agua",
            "Aleli",
            "Amarillo",
            "Ani/beige",
            "Ani/fux",
            "Aqua",
            "Avengers",
            "Azu/gris",
            "Azu/rosa",
            "Azul",
            "Barcos",
            "Bco/azu",
            "Bco/neg",
            "Beige",
            "Beige/corazon",
            "Black",
            "Blanco",
            "Bordo",
            "Bronce",
            "Cafe",
            "Camel",
            "Camuflado",
            "Canela",
            "Caramelo",
            "Celeste",
            "Cemento",
            "Champagne",
            "Charol",
            "Chocolate",
            "Coral",
            "Crema",
            "Crepe",
            "Crudo",
            "Cuadr/neg",
            "Cuadrille",
            "Cuadros",
            "Dorado",
            "Escoces",
            "Esmeralda",
            "Espiga",
            "Flor",
            "Flores",
            "Francia",
            "Frutilla",
            "Fucs/turq",
            "Fucsia",
            "Fuxcia",
            "Fuxcia/print",
            "Gliter",
            "Grafito",
            "Gris",
            "Gris/corazon",
            "Gris/rosa",
            "Indigo",
            "Iris",
            "Jean",
            "Jean/beige",
            "Jean/fucsia",
            "Jean/rojo",
            "Liberti",
            "Lila",
            "Marino",
            "Marron",
            "Maui",
            "Metalico",
            "Mickey",
            "Mostaza",
            "Multicolor",
            "Naranja",
            "Neg/bco",
            "Neg/beige",
            "Neg/fucsia",
            "Neg/fuxcia",
            "Neg/gris",
            "Neg/jean",
            "Neg/multi",
            "Negro",
            "Negro/gris",
            "Nude",
            "Oro",
            "Peppa",
            "Perla",
            "Petroleo",
            "Plata",
            "Reptil",
            "Roble",
            "Rojo",
            "Rosa",
            "Rosa/gris",
            "Rouge",
            "Sandia",
            "Selva",
            "Suela",
            "Tiza",
            "Topo",
            "Turquesa",
            "Unico",
            "Uva",
            "Verde",
            "Verde agua",
            "Violeta",
            "Vison",
            "White",
        ];
        foreach($colors as $color) {
            $new = new ShoeColor();
            $new->name = $color;
            $new->save();
        }
    }
}
